use module functions instead of Magic class
It will solve following:

Exception: attempting to use libmagic on multiple threads will end in
SEGV.  Prefer to use the module functions from_file or from_buffer, or
carefully manage direct use of the Magic class